#! /bin/sh

BASEDIR=$(dirname "$(readlink -f "$0")")

die() {
  echo "$1"
  exit 1
}


USERNAME=aur-builder
export AUR_LOCATION=https://aur.markridgwell.com

sudo pacman -Syu --noconfirm
sudo pacman -S --needed --noconfirm aurutils yay base-devel debugedit fakeroot jq util-linux

echo "Ensure $USERNAME exists"
if id "$USERNAME" >/dev/null 2>&1; then
    echo "* User $USERNAME found"
else
  echo "* User $USERNAME not found"
  sudo useradd \
       --create-home \
       --system \
       --user-group \
       --shell /bin/bash \
       --comment "AUR Builder" \
       "$USERNAME"
fi

echo "* Add user to sudoers"
echo "$USERNAME ALL=(ALL) NOPASSWD: ALL" | sudo tee "/etc/sudoers.d/$USERNAME"

echo "Create Repo"
[ -d "/srv/http/aur" ] || sudo sudo mkdir -p /srv/http/aur
[ -f "/srv/http/aur/aur.db.tar.bz2" ] || sudo repo-add /srv/http/aur/aur.db.tar.bz2
sudo chown "$USERNAME:$USERNAME" -R /srv/http/aur

echo "Updating systemd scripts"

echo "* credfeto-aur2repo-update-packages"
cat "$BASEDIR/systemd-unit/credfeto-aur2repo-update-packages.service" | sed "s:/home/markr/work/credfeto-aur2repo:$BASEDIR:g" | sudo tee /etc/systemd/system/credfeto-aur2repo-update-packages.service
sudo cp "$BASEDIR/systemd-unit/credfeto-aur2repo-update-packages.timer" /etc/systemd/system/credfeto-aur2repo-update-packages.timer
echo "  - Systemd reload"
sudo systemctl daemon-reload
echo "  - Enable credfeto-aur2repo-update-packages.timer"
sudo systemctl enable credfeto-aur2repo-update-packages.timer
echo "  - Start credfeto-aur2repo-update-packages.timer"
sudo systemctl start credfeto-aur2repo-update-packages.timer
